### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by adamcataldo** [adamcataldo/financy#10]
```
INFO:root:fetched balance_sheet for CEG
INFO:root:fetched market cap for CEG
INFO:root:fetched historic FCF for CEG
ERROR:root:Unexpected error on CEG
ERROR:root:Traceback (most recent call last):
  File "/Users/acataldo/Code/finance/financy/report_generator.py", line 41, in _rate_stock
    iv = valuation.value_stock(stock)
  File "/Users/acataldo/Code/finance/financy/valuation.py", line 107, in value_stock
    return value_asset(enterprise_value, quarterly_fcf)
  File "/Users/acataldo/Code/finance/financy/valuation.py", line 90, in value_asset
    growth_estimate = estimate_growth(annualized_fcf)
  File "/Users/acataldo/Code/finance/financy/valuation.py", line 41, in estimate_growth
    est = bootstrap((pct_change.dropna(),), np.mean, confidence_level=confidence_level)
  File "/Users/acataldo/Library/Python/3.8/lib/python/site-packages/scipy/stats/_bootstrap.py", line 445, in bootstrap
    args = _bootstrap_iv(data, statistic, vectorized, paired, axis,
  File "/Users/acataldo/Library/Python/3.8/lib/python/site-packages/scipy/stats/_bootstrap.py", line 158, in _bootstrap_iv
    raise ValueError("each sample in `data` must contain two or more "
ValueError: each sample in `data` must contain two or more observations along `axis`.
```

**Comment by adamcataldo** [comment]
The problem is that there are only three quarters of data.
