### ISSUE TITLE
New divide-by-zero error

### ISSUE THREAD

**Issue by adamcataldo** [adamcataldo/financy#9]
```
INFO:root:fetched balance_sheet for BK
INFO:root:fetched market cap for BK
INFO:root:fetched historic FCF for BK
ERROR:root:Unexpected error on BK
ERROR:root:Traceback (most recent call last):
  File "/Users/acataldo/Code/finance/financy/report_generator.py", line 42, in _rate_stock
    rating = rate_stock(iv, stock)
  File "/Users/acataldo/Code/finance/financy/report_generator.py", line 18, in rate_stock
    valuation_growth = iv.enterprise_value / iv.low_valuation
ZeroDivisionError: float division by zero
```

**Comment by adamcataldo** [comment]
Note, this is for a stock with negative enterprise value:

```
IntrinsicValue(low_valuation=0.0, high_valuation=267056498122.88007, enterprise_value=-100021838848, expected_growth_rate=0.027967868607497337)
```
